# Generated by Django 3.2.6 on 2022-04-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IGL_account',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('IGL_username', models.CharField(max_length=30, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('confirm_password', models.CharField(max_length=40)),
            ],
        ),
    ]
